# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pass_wd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
